### PR TITLE
Alternative concurrent evaluation of fields

### PR DESCRIPTION
**Pull request by andreas**
This is another take on doing concurrent evaluation of fields. Not necessarily better, but maybe it can serve as inspiration. The goroutines assign directly into the result map, which (unfortunately) needs to be protected by a mutex, as maps are not thread-safe. A separate channel `panics` is used for re-raising panics.

### CODE REVIEW

**Comment by sogko** [comment]
Hey @andreas 

Thanks for the PR, appreciate it very much 👍

Regarding the use of mutex for `finalResults` map, I think it's fine. The implementation reads easier now and consistent with `completeListValue`.

Cheers!

**Comment by Nebulai** [comment]
Hey @andreas @sogko,

Sorry for lurking, but any idea when parallel resolves might make it into master?
We're looking to implement GraphQL in the company I work at and I've been experimenting with the Golang version. Some colleagues want to go with the JavaScript implementation however and their main reasoning is that go-graphql doesn't have parallel resolves yet. 

I tried compiling the experiment-parallel-resolve branch unsuccessfully:

```
# graphql-go-parallel
../graphql-go-parallel/executor.go:183: undefined: ast.OperationTypeMutation

../graphql-go-parallel/executor.go:197: undefined: ast.OperationTypeQuery

../graphql-go-parallel/executor.go:199: undefined: ast.OperationTypeMutation

../graphql-go-parallel/executor.go:204: cannot use operation (type ast.Definition) as type ast.Node in array or slice literal:
    ast.Definition does not implement ast.Node (missing GetKind method)

../graphql-go-parallel/executor.go:209: too many arguments in call to gqlerrors.NewError

../graphql-go-parallel/executor.go:212: undefined: ast.OperationTypeSubscription

../graphql-go-parallel/executor.go:217: cannot use operation (type ast.Definition) as type ast.Node in array or slice literal:
    ast.Definition does not implement ast.Node (missing GetKind method)

../graphql-go-parallel/executor.go:222: too many arguments in call to gqlerrors.NewError

../graphql-go-parallel/executor.go:228: cannot use operation (type ast.Definition) as type ast.Node in array or slice literal:
    ast.Definition does not implement ast.Node (missing GetKind method)

../graphql-go-parallel/executor.go:233: too many arguments in call to gqlerrors.NewError

../graphql-go-parallel/executor.go:233: too many errors


```

Any idea what I'm doing wrong? Give me some pointers and maybe I can help solve it.

**Comment by andreas** [comment]
@Nebulai, the following works for me:

``` bash
git clone https://github.com/sogko/graphql.git
cd graphql
git checkout origin/sogko/experiment-parallel-resolve
go build
```

How did you get that error?

**Comment by Nebulai** [comment]
@andreas Got it working now

I had an old version of go-graphql. Pulled the latest one and just had this one error:

`./graphql.go:37: cannot use p.RequestString (type string) as type []byte in field value`

Changed line 37 to how it looks in the go-graphql master and that did the trick :+1:

**Pull request merged**
